/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mentalapp;

import javax.swing.JOptionPane;

/**
 *
 * @author marym
 */
public class QuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizGUI
     */
    public QuizGUI() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1 = new javax.swing.ButtonGroup();
        q2 = new javax.swing.ButtonGroup();
        q3 = new javax.swing.ButtonGroup();
        q4 = new javax.swing.ButtonGroup();
        q5 = new javax.swing.ButtonGroup();
        q6 = new javax.swing.ButtonGroup();
        q7 = new javax.swing.ButtonGroup();
        q8 = new javax.swing.ButtonGroup();
        q9 = new javax.swing.ButtonGroup();
        q10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        homeBTN = new javax.swing.JButton();
        groupLBL = new javax.swing.JLabel();
        desc1LBL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        desc3LBL = new javax.swing.JLabel();
        q1LBL = new javax.swing.JLabel();
        q2LBL = new javax.swing.JLabel();
        q3LBL = new javax.swing.JLabel();
        q4LBL = new javax.swing.JLabel();
        q5LBL = new javax.swing.JLabel();
        q6LBL = new javax.swing.JLabel();
        q7LBL = new javax.swing.JLabel();
        q8LBL = new javax.swing.JLabel();
        q9LBL = new javax.swing.JLabel();
        q10LBL = new javax.swing.JLabel();
        q1a1RB = new javax.swing.JRadioButton();
        q2a1RB = new javax.swing.JRadioButton();
        q3a1RB = new javax.swing.JRadioButton();
        q4a1RB = new javax.swing.JRadioButton();
        q5a1RB = new javax.swing.JRadioButton();
        q6a1RB = new javax.swing.JRadioButton();
        q7a1RB = new javax.swing.JRadioButton();
        q8a1RB = new javax.swing.JRadioButton();
        q9a1RB = new javax.swing.JRadioButton();
        q10a1RB = new javax.swing.JRadioButton();
        q1a2RB = new javax.swing.JRadioButton();
        q1a3RB = new javax.swing.JRadioButton();
        q1a4RB = new javax.swing.JRadioButton();
        q1a5RB = new javax.swing.JRadioButton();
        q2a2RB = new javax.swing.JRadioButton();
        q2a3RB = new javax.swing.JRadioButton();
        q2a4RB = new javax.swing.JRadioButton();
        q2a5RB = new javax.swing.JRadioButton();
        q3a2RB = new javax.swing.JRadioButton();
        q3a3RB = new javax.swing.JRadioButton();
        q3a4RB = new javax.swing.JRadioButton();
        q3a5RB = new javax.swing.JRadioButton();
        q4a2RB = new javax.swing.JRadioButton();
        q4a3RB = new javax.swing.JRadioButton();
        q4a4RB = new javax.swing.JRadioButton();
        q4a5RB = new javax.swing.JRadioButton();
        q5a2RB = new javax.swing.JRadioButton();
        q5a3RB = new javax.swing.JRadioButton();
        q5a4RB = new javax.swing.JRadioButton();
        q5a5RB = new javax.swing.JRadioButton();
        q6a2RB = new javax.swing.JRadioButton();
        q6a3RB = new javax.swing.JRadioButton();
        q6a4RB = new javax.swing.JRadioButton();
        q6a5RB = new javax.swing.JRadioButton();
        q7a2RB = new javax.swing.JRadioButton();
        q7a3RB = new javax.swing.JRadioButton();
        q7a4RB = new javax.swing.JRadioButton();
        q7a5RB = new javax.swing.JRadioButton();
        q8a2RB = new javax.swing.JRadioButton();
        q8a3RB = new javax.swing.JRadioButton();
        q8a4RB = new javax.swing.JRadioButton();
        q8a5RB = new javax.swing.JRadioButton();
        q9a2RB = new javax.swing.JRadioButton();
        q9a3RB = new javax.swing.JRadioButton();
        q9a4RB = new javax.swing.JRadioButton();
        q9a5RB = new javax.swing.JRadioButton();
        q10a2RB = new javax.swing.JRadioButton();
        q10a3RB = new javax.swing.JRadioButton();
        q10a4RB = new javax.swing.JRadioButton();
        q10a5RB = new javax.swing.JRadioButton();
        submitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(497, 100));

        titleLBL.setFont(new java.awt.Font("Rockwell Nova", 0, 36)); // NOI18N
        titleLBL.setText("Clarity ");

        homeBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeBTN.setText("Home");

        groupLBL.setText("Group 13 OOP Project");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(homeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(groupLBL)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(groupLBL))
        );

        desc1LBL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        desc1LBL.setText("This online screening is not a diagnostic tool. ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ANXIETY QUIZ");

        desc3LBL.setFont(new java.awt.Font("Verdana Pro", 1, 12)); // NOI18N
        desc3LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc3LBL.setText("1 = Not Present, 2 = Mild, 3 = Moderate, 4 = Severe, 5 = Very Severe");

        q1LBL.setText("1. Worries, fearful anticipation, irritability.");

        q2LBL.setText("2. Feelings of tension, fatigue, restlessness.");

        q3LBL.setText("3. Fear dark, strangers, being left alone, traffic, crowds.");

        q4LBL.setText("4. Difficulty in falling asleep, broken sleep.");

        q5LBL.setText("5. Difficulty in concentration, poor memory.");

        q6LBL.setText("6. Loss of interest, lack of pleasure in hobbies, early waking.");

        q7LBL.setText("7. Pains and aches, twitching, stiffness.");

        q8LBL.setText("8. Blurring of vision, hot and cold flushes, feelings of weakness.");

        q9LBL.setText("9. Palpitations, pain in chest, fainting feelings.");

        q10LBL.setText("10. Nausea, vomiting.");

        q1a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q1.add(q1a1RB);
        q1a1RB.setText("1");
        q1a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a1RBActionPerformed(evt);
            }
        });

        q2a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q2.add(q2a1RB);
        q2a1RB.setText("1");
        q2a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a1RBActionPerformed(evt);
            }
        });

        q3a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q3.add(q3a1RB);
        q3a1RB.setText("1");
        q3a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a1RBActionPerformed(evt);
            }
        });

        q4a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q4.add(q4a1RB);
        q4a1RB.setText("1");
        q4a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a1RBActionPerformed(evt);
            }
        });

        q5a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q5.add(q5a1RB);
        q5a1RB.setText("1");
        q5a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5a1RBActionPerformed(evt);
            }
        });

        q6a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q6.add(q6a1RB);
        q6a1RB.setText("1");
        q6a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6a1RBActionPerformed(evt);
            }
        });

        q7a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q7.add(q7a1RB);
        q7a1RB.setText("1");
        q7a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7a1RBActionPerformed(evt);
            }
        });

        q8a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q8.add(q8a1RB);
        q8a1RB.setText("1");
        q8a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8a1RBActionPerformed(evt);
            }
        });

        q9a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q9.add(q9a1RB);
        q9a1RB.setText("1");
        q9a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9a1RBActionPerformed(evt);
            }
        });

        q10a1RB.setBackground(new java.awt.Color(204, 204, 255));
        q10.add(q10a1RB);
        q10a1RB.setText("1");
        q10a1RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10a1RBActionPerformed(evt);
            }
        });

        q1a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q1.add(q1a2RB);
        q1a2RB.setText("2");
        q1a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a2RBActionPerformed(evt);
            }
        });

        q1a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q1.add(q1a3RB);
        q1a3RB.setText("3");
        q1a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a3RBActionPerformed(evt);
            }
        });

        q1a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q1.add(q1a4RB);
        q1a4RB.setText("4");
        q1a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a4RBActionPerformed(evt);
            }
        });

        q1a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q1.add(q1a5RB);
        q1a5RB.setText("5");
        q1a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a5RBActionPerformed(evt);
            }
        });

        q2a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q2.add(q2a2RB);
        q2a2RB.setText("2");
        q2a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a2RBActionPerformed(evt);
            }
        });

        q2a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q2.add(q2a3RB);
        q2a3RB.setText("3");
        q2a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a3RBActionPerformed(evt);
            }
        });

        q2a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q2.add(q2a4RB);
        q2a4RB.setText("4");
        q2a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a4RBActionPerformed(evt);
            }
        });

        q2a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q2.add(q2a5RB);
        q2a5RB.setText("5");
        q2a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a5RBActionPerformed(evt);
            }
        });

        q3a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q3.add(q3a2RB);
        q3a2RB.setText("2");
        q3a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a2RBActionPerformed(evt);
            }
        });

        q3a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q3.add(q3a3RB);
        q3a3RB.setText("3");
        q3a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a3RBActionPerformed(evt);
            }
        });

        q3a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q3.add(q3a4RB);
        q3a4RB.setText("4");
        q3a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a4RBActionPerformed(evt);
            }
        });

        q3a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q3.add(q3a5RB);
        q3a5RB.setText("5");
        q3a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a5RBActionPerformed(evt);
            }
        });

        q4a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q4.add(q4a2RB);
        q4a2RB.setText("2");
        q4a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a2RBActionPerformed(evt);
            }
        });

        q4a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q4.add(q4a3RB);
        q4a3RB.setText("3");
        q4a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a3RBActionPerformed(evt);
            }
        });

        q4a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q4.add(q4a4RB);
        q4a4RB.setText("4");
        q4a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a4RBActionPerformed(evt);
            }
        });

        q4a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q4.add(q4a5RB);
        q4a5RB.setText("5");
        q4a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a5RBActionPerformed(evt);
            }
        });

        q5a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q5.add(q5a2RB);
        q5a2RB.setText("2");
        q5a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5a2RBActionPerformed(evt);
            }
        });

        q5a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q5.add(q5a3RB);
        q5a3RB.setText("3");
        q5a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5a3RBActionPerformed(evt);
            }
        });

        q5a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q5.add(q5a4RB);
        q5a4RB.setText("4");
        q5a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5a4RBActionPerformed(evt);
            }
        });

        q5a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q5.add(q5a5RB);
        q5a5RB.setText("5");
        q5a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5a5RBActionPerformed(evt);
            }
        });

        q6a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q6.add(q6a2RB);
        q6a2RB.setText("2");
        q6a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6a2RBActionPerformed(evt);
            }
        });

        q6a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q6.add(q6a3RB);
        q6a3RB.setText("3");
        q6a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6a3RBActionPerformed(evt);
            }
        });

        q6a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q6.add(q6a4RB);
        q6a4RB.setText("4");
        q6a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6a4RBActionPerformed(evt);
            }
        });

        q6a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q6.add(q6a5RB);
        q6a5RB.setText("5");
        q6a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6a5RBActionPerformed(evt);
            }
        });

        q7a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q7.add(q7a2RB);
        q7a2RB.setText("2");
        q7a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7a2RBActionPerformed(evt);
            }
        });

        q7a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q7.add(q7a3RB);
        q7a3RB.setText("3");
        q7a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7a3RBActionPerformed(evt);
            }
        });

        q7a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q7.add(q7a4RB);
        q7a4RB.setText("4");
        q7a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7a4RBActionPerformed(evt);
            }
        });

        q7a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q7.add(q7a5RB);
        q7a5RB.setText("5");
        q7a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7a5RBActionPerformed(evt);
            }
        });

        q8a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q8.add(q8a2RB);
        q8a2RB.setText("2");
        q8a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8a2RBActionPerformed(evt);
            }
        });

        q8a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q8.add(q8a3RB);
        q8a3RB.setText("3");
        q8a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8a3RBActionPerformed(evt);
            }
        });

        q8a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q8.add(q8a4RB);
        q8a4RB.setText("4");
        q8a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8a4RBActionPerformed(evt);
            }
        });

        q8a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q8.add(q8a5RB);
        q8a5RB.setText("5");
        q8a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8a5RBActionPerformed(evt);
            }
        });

        q9a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q9.add(q9a2RB);
        q9a2RB.setText("2");
        q9a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9a2RBActionPerformed(evt);
            }
        });

        q9a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q9.add(q9a3RB);
        q9a3RB.setText("3");
        q9a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9a3RBActionPerformed(evt);
            }
        });

        q9a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q9.add(q9a4RB);
        q9a4RB.setText("4");
        q9a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9a4RBActionPerformed(evt);
            }
        });

        q9a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q9.add(q9a5RB);
        q9a5RB.setText("5");
        q9a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9a5RBActionPerformed(evt);
            }
        });

        q10a2RB.setBackground(new java.awt.Color(204, 204, 255));
        q10.add(q10a2RB);
        q10a2RB.setText("2");
        q10a2RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10a2RBActionPerformed(evt);
            }
        });

        q10a3RB.setBackground(new java.awt.Color(204, 204, 255));
        q10.add(q10a3RB);
        q10a3RB.setText("3");
        q10a3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10a3RBActionPerformed(evt);
            }
        });

        q10a4RB.setBackground(new java.awt.Color(204, 204, 255));
        q10.add(q10a4RB);
        q10a4RB.setText("4");
        q10a4RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10a4RBActionPerformed(evt);
            }
        });

        q10a5RB.setBackground(new java.awt.Color(204, 204, 255));
        q10.add(q10a5RB);
        q10a5RB.setText("5");
        q10a5RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10a5RBActionPerformed(evt);
            }
        });

        submitBTN.setBackground(new java.awt.Color(0, 0, 0));
        submitBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBTN.setForeground(new java.awt.Color(255, 255, 255));
        submitBTN.setText("Submit");
        submitBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        submitBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(desc3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(desc1LBL)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q1LBL)
                                    .addComponent(q2LBL)
                                    .addComponent(q3LBL)
                                    .addComponent(q4LBL)
                                    .addComponent(q5LBL)
                                    .addComponent(q6LBL)
                                    .addComponent(q7LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q9LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(q8LBL)
                                    .addComponent(q10LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q1a1RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q1a2RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q1a3RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q1a4RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q1a5RB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q2a1RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q2a2RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q2a3RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q2a4RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q2a5RB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(q3a1RB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(q3a2RB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(q3a3RB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(q3a4RB))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(q5a1RB)
                                                    .addComponent(q4a1RB))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(q4a2RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q4a3RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q4a4RB))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(q5a2RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q5a3RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q5a4RB))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(q7a1RB)
                                                    .addComponent(q6a1RB))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(q6a2RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q6a3RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q6a4RB))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(q7a2RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q7a3RB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(q7a4RB)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(q4a5RB)
                                            .addComponent(q3a5RB)
                                            .addComponent(q5a5RB)
                                            .addComponent(q6a5RB)
                                            .addComponent(q7a5RB)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(q9a1RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q9a2RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q9a3RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q9a4RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(q9a5RB))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(q8a1RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q8a2RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q8a3RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q8a4RB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q8a5RB))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q10a1RB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q10a2RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q10a3RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q10a4RB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q10a5RB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1LBL)
                    .addComponent(q1a1RB)
                    .addComponent(q1a2RB)
                    .addComponent(q1a3RB)
                    .addComponent(q1a4RB)
                    .addComponent(q1a5RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2LBL)
                    .addComponent(q2a1RB)
                    .addComponent(q2a2RB)
                    .addComponent(q2a3RB)
                    .addComponent(q2a4RB)
                    .addComponent(q2a5RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3LBL)
                    .addComponent(q3a1RB)
                    .addComponent(q3a2RB)
                    .addComponent(q3a3RB)
                    .addComponent(q3a4RB)
                    .addComponent(q3a5RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4LBL)
                    .addComponent(q4a5RB)
                    .addComponent(q4a4RB)
                    .addComponent(q4a3RB)
                    .addComponent(q4a2RB)
                    .addComponent(q4a1RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5LBL)
                    .addComponent(q5a1RB)
                    .addComponent(q5a2RB)
                    .addComponent(q5a3RB)
                    .addComponent(q5a4RB)
                    .addComponent(q5a5RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6LBL)
                    .addComponent(q6a5RB)
                    .addComponent(q6a4RB)
                    .addComponent(q6a3RB)
                    .addComponent(q6a2RB)
                    .addComponent(q6a1RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7LBL)
                    .addComponent(q7a1RB)
                    .addComponent(q7a2RB)
                    .addComponent(q7a3RB)
                    .addComponent(q7a4RB)
                    .addComponent(q7a5RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8LBL)
                    .addComponent(q8a1RB)
                    .addComponent(q8a2RB)
                    .addComponent(q8a3RB)
                    .addComponent(q8a4RB)
                    .addComponent(q8a5RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9LBL)
                    .addComponent(q9a1RB)
                    .addComponent(q9a2RB)
                    .addComponent(q9a3RB)
                    .addComponent(q9a5RB)
                    .addComponent(q9a4RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10LBL)
                    .addComponent(q10a1RB)
                    .addComponent(q10a2RB)
                    .addComponent(q10a3RB)
                    .addComponent(q10a5RB)
                    .addComponent(q10a4RB))
                .addGap(18, 18, 18)
                .addComponent(submitBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        if (!(
    (q1a1RB.isSelected() || q1a2RB.isSelected() || q1a3RB.isSelected() || q1a4RB.isSelected()) &&
    (q2a1RB.isSelected() || q2a2RB.isSelected() || q2a3RB.isSelected() || q2a4RB.isSelected()) &&
    (q3a1RB.isSelected() || q3a2RB.isSelected() || q3a3RB.isSelected() || q3a4RB.isSelected()) &&
    (q4a1RB.isSelected() || q4a2RB.isSelected() || q4a3RB.isSelected() || q4a4RB.isSelected()) &&
    (q5a1RB.isSelected() || q5a2RB.isSelected() || q5a3RB.isSelected() || q5a4RB.isSelected()) &&
    (q6a1RB.isSelected() || q6a2RB.isSelected() || q6a3RB.isSelected() || q6a4RB.isSelected()) &&
    (q7a1RB.isSelected() || q7a2RB.isSelected() || q7a3RB.isSelected() || q7a4RB.isSelected()) &&
    (q8a1RB.isSelected() || q8a2RB.isSelected() || q8a3RB.isSelected() || q8a4RB.isSelected()) &&
    (q9a1RB.isSelected() || q9a2RB.isSelected() || q9a3RB.isSelected() || q9a4RB.isSelected()) &&
    (q10a1RB.isSelected() || q10a2RB.isSelected() || q10a3RB.isSelected() || q10a4RB.isSelected())
)) {
    JOptionPane.showMessageDialog(null, "Please answer all questions");
} else {
            //lock buttons
            q1a1RB.setEnabled(false);
            q1a2RB.setEnabled(false);
            q1a3RB.setEnabled(false);
            q1a4RB.setEnabled(false);
            q1a5RB.setEnabled(false);

            q2a1RB.setEnabled(false);
            q2a2RB.setEnabled(false);
            q2a3RB.setEnabled(false);
            q2a4RB.setEnabled(false);
            q2a5RB.setEnabled(false);

            q3a1RB.setEnabled(false);
            q3a2RB.setEnabled(false);
            q3a3RB.setEnabled(false);
            q3a4RB.setEnabled(false);
            q3a5RB.setEnabled(false);

            q4a1RB.setEnabled(false);
            q4a2RB.setEnabled(false);
            q4a3RB.setEnabled(false);
            q4a4RB.setEnabled(false);
            q4a5RB.setEnabled(false);

            q5a1RB.setEnabled(false);
            q5a2RB.setEnabled(false);
            q5a3RB.setEnabled(false);
            q5a4RB.setEnabled(false);
            q5a5RB.setEnabled(false);

            q6a1RB.setEnabled(false);
            q6a2RB.setEnabled(false);
            q6a3RB.setEnabled(false);
            q6a4RB.setEnabled(false);
            q6a5RB.setEnabled(false);

            q7a1RB.setEnabled(false);
            q7a2RB.setEnabled(false);
            q7a3RB.setEnabled(false);
            q7a4RB.setEnabled(false);
            q7a5RB.setEnabled(false);

            q8a1RB.setEnabled(false);
            q8a2RB.setEnabled(false);
            q8a3RB.setEnabled(false);
            q8a4RB.setEnabled(false);
            q8a5RB.setEnabled(false);

            q9a1RB.setEnabled(false);
            q9a2RB.setEnabled(false);
            q9a3RB.setEnabled(false);
            q9a4RB.setEnabled(false);
            q9a5RB.setEnabled(false);

            q10a1RB.setEnabled(false);
            q10a2RB.setEnabled(false);
            q10a3RB.setEnabled(false);
            q10a4RB.setEnabled(false);
            q10a5RB.setEnabled(false);

        }

     {
          
        varibleResult = varible1 + varible2 + varible3 + varible4 + varible5 + varible6 + varible7 + varible8 + varible9 + varible10;

        if (varibleResult < 50 && varibleResult >= 15) {
            JOptionPane.showMessageDialog(null, "There is a chance you have anxiety. Please note this online screening is not a diagnostic tool.");
        } else {
            JOptionPane.showMessageDialog(null, "There is a chance you don't have diagnosed anxiety. Please note this online screening is not a diagnostic tool.");
        }
}


    }//GEN-LAST:event_submitBTNActionPerformed

    private void q10a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10a3RBActionPerformed
        // TODO add your handling code here:
        varible10 = 3;
    }//GEN-LAST:event_q10a3RBActionPerformed

    private void q4a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a5RBActionPerformed
        // TODO add your handling code here:
        varible4 = 5;
    }//GEN-LAST:event_q4a5RBActionPerformed

    private void q3a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a3RBActionPerformed
        // TODO add your handling code here:
        varible3 = 3;
    }//GEN-LAST:event_q3a3RBActionPerformed

    private void q1a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a2RBActionPerformed
        // TODO add your handling code here:
        varible1 = 2;
    }//GEN-LAST:event_q1a2RBActionPerformed

    private void q5a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5a1RBActionPerformed
        // TODO add your handling code here:
        varible5 = 1;
    }//GEN-LAST:event_q5a1RBActionPerformed

    private void q1a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a1RBActionPerformed
        // TODO add your handling code here:

        varible1 = 1;
    }//GEN-LAST:event_q1a1RBActionPerformed

    private void q1a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a3RBActionPerformed
        // TODO add your handling code here:
        varible1 = 3;
    }//GEN-LAST:event_q1a3RBActionPerformed

    private void q1a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a4RBActionPerformed
        // TODO add your handling code here:
        varible1 = 4;
    }//GEN-LAST:event_q1a4RBActionPerformed

    private void q1a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a5RBActionPerformed
        // TODO add your handling code here:
        varible1 = 5;
    }//GEN-LAST:event_q1a5RBActionPerformed

    private void q2a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a1RBActionPerformed
        // TODO add your handling code here:
        varible2 = 1;
    }//GEN-LAST:event_q2a1RBActionPerformed

    private void q2a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a2RBActionPerformed
        // TODO add your handling code here:
        varible2 = 2;
    }//GEN-LAST:event_q2a2RBActionPerformed

    private void q2a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a3RBActionPerformed
        // TODO add your handling code here:
        varible2 = 3;
    }//GEN-LAST:event_q2a3RBActionPerformed

    private void q2a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a4RBActionPerformed
        // TODO add your handling code here:
        varible2 = 4;
    }//GEN-LAST:event_q2a4RBActionPerformed

    private void q2a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a5RBActionPerformed
        // TODO add your handling code here:
        varible2 = 5;
    }//GEN-LAST:event_q2a5RBActionPerformed

    private void q3a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a1RBActionPerformed
        // TODO add your handling code here:
        varible3 = 1;
    }//GEN-LAST:event_q3a1RBActionPerformed

    private void q3a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a2RBActionPerformed
        // TODO add your handling code here:
        varible3 = 2;
    }//GEN-LAST:event_q3a2RBActionPerformed

    private void q3a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a4RBActionPerformed
        // TODO add your handling code here:
        varible3 = 4;
    }//GEN-LAST:event_q3a4RBActionPerformed

    private void q3a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a5RBActionPerformed
        // TODO add your handling code here:
        varible3 = 5;
    }//GEN-LAST:event_q3a5RBActionPerformed

    private void q4a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a1RBActionPerformed
        // TODO add your handling code here:
        varible4 = 1;
    }//GEN-LAST:event_q4a1RBActionPerformed

    private void q4a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a2RBActionPerformed
        // TODO add your handling code here:
        varible4 = 2;
    }//GEN-LAST:event_q4a2RBActionPerformed

    private void q4a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a3RBActionPerformed
        // TODO add your handling code here:
        varible4 = 3;
    }//GEN-LAST:event_q4a3RBActionPerformed

    private void q4a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a4RBActionPerformed
        // TODO add your handling code here:
        varible4 = 4;
    }//GEN-LAST:event_q4a4RBActionPerformed

    private void q5a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5a2RBActionPerformed
        // TODO add your handling code here:
        varible5 = 2;
    }//GEN-LAST:event_q5a2RBActionPerformed

    private void q5a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5a3RBActionPerformed
        // TODO add your handling code here:
        varible5 = 3;
    }//GEN-LAST:event_q5a3RBActionPerformed

    private void q5a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5a4RBActionPerformed
        // TODO add your handling code here:
        varible5 = 4;
    }//GEN-LAST:event_q5a4RBActionPerformed

    private void q5a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5a5RBActionPerformed
        // TODO add your handling code here:
        varible5 = 5;
    }//GEN-LAST:event_q5a5RBActionPerformed

    private void q6a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6a1RBActionPerformed
        // TODO add your handling code here:
        varible6 = 1;
    }//GEN-LAST:event_q6a1RBActionPerformed

    private void q6a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6a2RBActionPerformed
        // TODO add your handling code here:
        varible6 = 2;
    }//GEN-LAST:event_q6a2RBActionPerformed

    private void q6a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6a3RBActionPerformed
        // TODO add your handling code here:
        varible6 = 3;
    }//GEN-LAST:event_q6a3RBActionPerformed

    private void q6a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6a4RBActionPerformed
        // TODO add your handling code here:
        varible6 = 4;
    }//GEN-LAST:event_q6a4RBActionPerformed

    private void q6a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6a5RBActionPerformed
        // TODO add your handling code here:
        varible6 = 5;
    }//GEN-LAST:event_q6a5RBActionPerformed

    private void q7a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7a1RBActionPerformed
        // TODO add your handling code here:
        varible7 = 1;
    }//GEN-LAST:event_q7a1RBActionPerformed

    private void q7a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7a2RBActionPerformed
        // TODO add your handling code here:
        varible7 = 2;
    }//GEN-LAST:event_q7a2RBActionPerformed

    private void q7a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7a3RBActionPerformed
        // TODO add your handling code here:
        varible7 = 3;
    }//GEN-LAST:event_q7a3RBActionPerformed

    private void q7a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7a4RBActionPerformed
        // TODO add your handling code here:
        varible7 = 4;
    }//GEN-LAST:event_q7a4RBActionPerformed

    private void q7a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7a5RBActionPerformed
        // TODO add your handling code here:
        varible7 = 5;
    }//GEN-LAST:event_q7a5RBActionPerformed

    private void q8a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8a1RBActionPerformed
        // TODO add your handling code here:
        varible8 = 1;
    }//GEN-LAST:event_q8a1RBActionPerformed

    private void q8a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8a2RBActionPerformed
        // TODO add your handling code here:
        varible8 = 2;
    }//GEN-LAST:event_q8a2RBActionPerformed

    private void q8a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8a3RBActionPerformed
        // TODO add your handling code here:
        varible8 = 3;
    }//GEN-LAST:event_q8a3RBActionPerformed

    private void q8a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8a4RBActionPerformed
        // TODO add your handling code here:
        varible8 = 4;
    }//GEN-LAST:event_q8a4RBActionPerformed

    private void q8a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8a5RBActionPerformed
        // TODO add your handling code here:
        varible8 = 5;
    }//GEN-LAST:event_q8a5RBActionPerformed

    private void q9a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9a1RBActionPerformed
        // TODO add your handling code here:
        varible9 = 1;
    }//GEN-LAST:event_q9a1RBActionPerformed

    private void q9a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9a2RBActionPerformed
        // TODO add your handling code here:
        varible9 = 2;
    }//GEN-LAST:event_q9a2RBActionPerformed

    private void q9a3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9a3RBActionPerformed
        // TODO add your handling code here:
        varible9 = 3;
    }//GEN-LAST:event_q9a3RBActionPerformed

    private void q9a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9a4RBActionPerformed
        // TODO add your handling code here:
        varible9 = 4;
    }//GEN-LAST:event_q9a4RBActionPerformed

    private void q9a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9a5RBActionPerformed
        // TODO add your handling code here:
        varible9 = 5;
    }//GEN-LAST:event_q9a5RBActionPerformed

    private void q10a1RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10a1RBActionPerformed
        // TODO add your handling code here:
        varible10 = 1;
    }//GEN-LAST:event_q10a1RBActionPerformed

    private void q10a2RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10a2RBActionPerformed
        // TODO add your handling code here:
        varible10 = 2;
    }//GEN-LAST:event_q10a2RBActionPerformed

    private void q10a4RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10a4RBActionPerformed
        // TODO add your handling code here:
        varible10 = 4;
    }//GEN-LAST:event_q10a4RBActionPerformed

    private void q10a5RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10a5RBActionPerformed
        // TODO add your handling code here:
        varible10 = 5;
    }//GEN-LAST:event_q10a5RBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desc1LBL;
    private javax.swing.JLabel desc3LBL;
    private javax.swing.JLabel groupLBL;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup q1;
    private javax.swing.ButtonGroup q10;
    private javax.swing.JLabel q10LBL;
    private javax.swing.JRadioButton q10a1RB;
    private javax.swing.JRadioButton q10a2RB;
    private javax.swing.JRadioButton q10a3RB;
    private javax.swing.JRadioButton q10a4RB;
    private javax.swing.JRadioButton q10a5RB;
    private javax.swing.JLabel q1LBL;
    private javax.swing.JRadioButton q1a1RB;
    private javax.swing.JRadioButton q1a2RB;
    private javax.swing.JRadioButton q1a3RB;
    private javax.swing.JRadioButton q1a4RB;
    private javax.swing.JRadioButton q1a5RB;
    private javax.swing.ButtonGroup q2;
    private javax.swing.JLabel q2LBL;
    private javax.swing.JRadioButton q2a1RB;
    private javax.swing.JRadioButton q2a2RB;
    private javax.swing.JRadioButton q2a3RB;
    private javax.swing.JRadioButton q2a4RB;
    private javax.swing.JRadioButton q2a5RB;
    private javax.swing.ButtonGroup q3;
    private javax.swing.JLabel q3LBL;
    private javax.swing.JRadioButton q3a1RB;
    private javax.swing.JRadioButton q3a2RB;
    private javax.swing.JRadioButton q3a3RB;
    private javax.swing.JRadioButton q3a4RB;
    private javax.swing.JRadioButton q3a5RB;
    private javax.swing.ButtonGroup q4;
    private javax.swing.JLabel q4LBL;
    private javax.swing.JRadioButton q4a1RB;
    private javax.swing.JRadioButton q4a2RB;
    private javax.swing.JRadioButton q4a3RB;
    private javax.swing.JRadioButton q4a4RB;
    private javax.swing.JRadioButton q4a5RB;
    private javax.swing.ButtonGroup q5;
    private javax.swing.JLabel q5LBL;
    private javax.swing.JRadioButton q5a1RB;
    private javax.swing.JRadioButton q5a2RB;
    private javax.swing.JRadioButton q5a3RB;
    private javax.swing.JRadioButton q5a4RB;
    private javax.swing.JRadioButton q5a5RB;
    private javax.swing.ButtonGroup q6;
    private javax.swing.JLabel q6LBL;
    private javax.swing.JRadioButton q6a1RB;
    private javax.swing.JRadioButton q6a2RB;
    private javax.swing.JRadioButton q6a3RB;
    private javax.swing.JRadioButton q6a4RB;
    private javax.swing.JRadioButton q6a5RB;
    private javax.swing.ButtonGroup q7;
    private javax.swing.JLabel q7LBL;
    private javax.swing.JRadioButton q7a1RB;
    private javax.swing.JRadioButton q7a2RB;
    private javax.swing.JRadioButton q7a3RB;
    private javax.swing.JRadioButton q7a4RB;
    private javax.swing.JRadioButton q7a5RB;
    private javax.swing.ButtonGroup q8;
    private javax.swing.JLabel q8LBL;
    private javax.swing.JRadioButton q8a1RB;
    private javax.swing.JRadioButton q8a2RB;
    private javax.swing.JRadioButton q8a3RB;
    private javax.swing.JRadioButton q8a4RB;
    private javax.swing.JRadioButton q8a5RB;
    private javax.swing.ButtonGroup q9;
    private javax.swing.JLabel q9LBL;
    private javax.swing.JRadioButton q9a1RB;
    private javax.swing.JRadioButton q9a2RB;
    private javax.swing.JRadioButton q9a3RB;
    private javax.swing.JRadioButton q9a4RB;
    private javax.swing.JRadioButton q9a5RB;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
private static int varible1 = 0;
    private static int varible2 = 0;
    private static int varible3 = 0;
    private static int varible4 = 0;
    private static int varible5 = 0;
    private static int varible6 = 0;
    private static int varible7 = 0;
    private static int varible8 = 0;
    private static int varible9 = 0;
    private static int varible10 = 0;
    private static int varibleResult;
}
