/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clarityapp;

/**
 *
 * @author Andre
 */
public class FormJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FormJFrame
     */
    public FormJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        sleepLbl = new javax.swing.JLabel();
        physicalLbl = new javax.swing.JLabel();
        socialLbl = new javax.swing.JLabel();
        hobbyLbl = new javax.swing.JLabel();
        energyLbl = new javax.swing.JLabel();
        stressLbl = new javax.swing.JLabel();
        drinkLbl = new javax.swing.JLabel();
        smokeLbl = new javax.swing.JLabel();
        f11Btn = new javax.swing.JRadioButton();
        f12Btn = new javax.swing.JRadioButton();
        f13Btn = new javax.swing.JRadioButton();
        f14Btn = new javax.swing.JRadioButton();
        f15Btn = new javax.swing.JRadioButton();
        f16Btn = new javax.swing.JRadioButton();
        f17Btn = new javax.swing.JRadioButton();
        f18Btn = new javax.swing.JRadioButton();
        f21Btn = new javax.swing.JRadioButton();
        f22Btn = new javax.swing.JRadioButton();
        f23Btn = new javax.swing.JRadioButton();
        f24Btn = new javax.swing.JRadioButton();
        f25Btn = new javax.swing.JRadioButton();
        f26Btn = new javax.swing.JRadioButton();
        f27Btn = new javax.swing.JRadioButton();
        f28Btn = new javax.swing.JRadioButton();
        f31Btn = new javax.swing.JRadioButton();
        f32Btn = new javax.swing.JRadioButton();
        f33Btn = new javax.swing.JRadioButton();
        f34Btn = new javax.swing.JRadioButton();
        f35Btn = new javax.swing.JRadioButton();
        f36Btn = new javax.swing.JRadioButton();
        f37Btn = new javax.swing.JRadioButton();
        f38Btn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sleepLbl.setText("Do you not get enough Sleep?");

        physicalLbl.setText("Do you not do Physical Activities?");

        socialLbl.setText("How bad is your Socialising Skills?");

        hobbyLbl.setText("Are your Hobbies Harmful?");

        energyLbl.setText("How bad are your Energy Levels?");

        stressLbl.setText("How bad is your Stress?");

        drinkLbl.setText("Do you like to Drink Alcohol?");

        smokeLbl.setText("Do you Smoke?");

        buttonGroup1.add(f11Btn);
        f11Btn.setText("1");
        f11Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f11BtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(f12Btn);
        f12Btn.setText("1");

        buttonGroup3.add(f13Btn);
        f13Btn.setText("1");

        buttonGroup4.add(f14Btn);
        f14Btn.setText("1");

        buttonGroup5.add(f15Btn);
        f15Btn.setText("1");

        buttonGroup6.add(f16Btn);
        f16Btn.setText("1");

        buttonGroup7.add(f17Btn);
        f17Btn.setText("1");

        buttonGroup8.add(f18Btn);
        f18Btn.setText("1");

        buttonGroup1.add(f21Btn);
        f21Btn.setText("2");
        f21Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f21BtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(f22Btn);
        f22Btn.setText("2");
        f22Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f22BtnActionPerformed(evt);
            }
        });

        buttonGroup3.add(f23Btn);
        f23Btn.setText("2");
        f23Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f23BtnActionPerformed(evt);
            }
        });

        buttonGroup4.add(f24Btn);
        f24Btn.setText("2");
        f24Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f24BtnActionPerformed(evt);
            }
        });

        buttonGroup5.add(f25Btn);
        f25Btn.setText("2");
        f25Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f25BtnActionPerformed(evt);
            }
        });

        buttonGroup6.add(f26Btn);
        f26Btn.setText("2");
        f26Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f26BtnActionPerformed(evt);
            }
        });

        buttonGroup7.add(f27Btn);
        f27Btn.setText("2");
        f27Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f27BtnActionPerformed(evt);
            }
        });

        buttonGroup8.add(f28Btn);
        f28Btn.setText("2");
        f28Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f28BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(f31Btn);
        f31Btn.setText("3");
        f31Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f31BtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(f32Btn);
        f32Btn.setText("3");
        f32Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f32BtnActionPerformed(evt);
            }
        });

        buttonGroup3.add(f33Btn);
        f33Btn.setText("3");
        f33Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f33BtnActionPerformed(evt);
            }
        });

        buttonGroup4.add(f34Btn);
        f34Btn.setText("3");
        f34Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f34BtnActionPerformed(evt);
            }
        });

        buttonGroup5.add(f35Btn);
        f35Btn.setText("3");
        f35Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f35BtnActionPerformed(evt);
            }
        });

        buttonGroup7.add(f36Btn);
        f36Btn.setText("3");
        f36Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f36BtnActionPerformed(evt);
            }
        });

        buttonGroup6.add(f37Btn);
        f37Btn.setText("3");
        f37Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f37BtnActionPerformed(evt);
            }
        });

        buttonGroup8.add(f38Btn);
        f38Btn.setText("3");
        f38Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f38BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sleepLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(physicalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(socialLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hobbyLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(energyLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drinkLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(smokeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(f11Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f21Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f18Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f17Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f16Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f15Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f14Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f13Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f12Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f22Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f23Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f24Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f25Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f26Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f27Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f28Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f32Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f33Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f34Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f35Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f36Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f37Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f38Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(f31Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleepLbl)
                    .addComponent(f11Btn)
                    .addComponent(f31Btn)
                    .addComponent(f21Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicalLbl)
                    .addComponent(f12Btn)
                    .addComponent(f22Btn)
                    .addComponent(f32Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socialLbl)
                    .addComponent(f13Btn)
                    .addComponent(f23Btn)
                    .addComponent(f33Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hobbyLbl)
                    .addComponent(f14Btn)
                    .addComponent(f24Btn)
                    .addComponent(f34Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(energyLbl)
                    .addComponent(f15Btn)
                    .addComponent(f25Btn)
                    .addComponent(f35Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stressLbl)
                    .addComponent(f16Btn)
                    .addComponent(f26Btn)
                    .addComponent(f37Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drinkLbl)
                    .addComponent(f17Btn)
                    .addComponent(f27Btn)
                    .addComponent(f36Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smokeLbl)
                    .addComponent(f18Btn)
                    .addComponent(f28Btn)
                    .addComponent(f38Btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClarityGUI cg= new ClarityGUI();
        cg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void f11BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f11BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f11BtnActionPerformed

    private void f22BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f22BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f22BtnActionPerformed

    private void f31BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f31BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f31BtnActionPerformed

    private void f21BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f21BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f21BtnActionPerformed

    private void f23BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f23BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f23BtnActionPerformed

    private void f24BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f24BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f24BtnActionPerformed

    private void f25BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f25BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f25BtnActionPerformed

    private void f26BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f26BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f26BtnActionPerformed

    private void f27BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f27BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f27BtnActionPerformed

    private void f28BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f28BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f28BtnActionPerformed

    private void f32BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f32BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f32BtnActionPerformed

    private void f33BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f33BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f33BtnActionPerformed

    private void f34BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f34BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f34BtnActionPerformed

    private void f35BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f35BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f35BtnActionPerformed

    private void f36BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f36BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f36BtnActionPerformed

    private void f37BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f37BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f37BtnActionPerformed

    private void f38BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f38BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f38BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel drinkLbl;
    private javax.swing.JLabel energyLbl;
    private javax.swing.JRadioButton f11Btn;
    private javax.swing.JRadioButton f12Btn;
    private javax.swing.JRadioButton f13Btn;
    private javax.swing.JRadioButton f14Btn;
    private javax.swing.JRadioButton f15Btn;
    private javax.swing.JRadioButton f16Btn;
    private javax.swing.JRadioButton f17Btn;
    private javax.swing.JRadioButton f18Btn;
    private javax.swing.JRadioButton f21Btn;
    private javax.swing.JRadioButton f22Btn;
    private javax.swing.JRadioButton f23Btn;
    private javax.swing.JRadioButton f24Btn;
    private javax.swing.JRadioButton f25Btn;
    private javax.swing.JRadioButton f26Btn;
    private javax.swing.JRadioButton f27Btn;
    private javax.swing.JRadioButton f28Btn;
    private javax.swing.JRadioButton f31Btn;
    private javax.swing.JRadioButton f32Btn;
    private javax.swing.JRadioButton f33Btn;
    private javax.swing.JRadioButton f34Btn;
    private javax.swing.JRadioButton f35Btn;
    private javax.swing.JRadioButton f36Btn;
    private javax.swing.JRadioButton f37Btn;
    private javax.swing.JRadioButton f38Btn;
    private javax.swing.JLabel hobbyLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel physicalLbl;
    private javax.swing.JLabel sleepLbl;
    private javax.swing.JLabel smokeLbl;
    private javax.swing.JLabel socialLbl;
    private javax.swing.JLabel stressLbl;
    // End of variables declaration//GEN-END:variables
}
