/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healthformapp;

/*Andre Github Main*/
/*Andre Author*/

import javax.swing.JOptionPane;

public class FormJFrame extends javax.swing.JFrame {
    
    int formanswered = 0;
    int marks = 0;  
    
    public FormJFrame() {
        initComponents();     
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        f12Btn = new javax.swing.JRadioButton();
        f13Btn = new javax.swing.JRadioButton();
        f38Btn = new javax.swing.JRadioButton();
        f14Btn = new javax.swing.JRadioButton();
        f15Btn = new javax.swing.JRadioButton();
        f16Btn = new javax.swing.JRadioButton();
        f17Btn = new javax.swing.JRadioButton();
        f18Btn = new javax.swing.JRadioButton();
        f21Btn = new javax.swing.JRadioButton();
        f22Btn = new javax.swing.JRadioButton();
        f23Btn = new javax.swing.JRadioButton();
        f24Btn = new javax.swing.JRadioButton();
        f25Btn = new javax.swing.JRadioButton();
        f26Btn = new javax.swing.JRadioButton();
        f27Btn = new javax.swing.JRadioButton();
        f28Btn = new javax.swing.JRadioButton();
        f31Btn = new javax.swing.JRadioButton();
        f32Btn = new javax.swing.JRadioButton();
        f33Btn = new javax.swing.JRadioButton();
        f34Btn = new javax.swing.JRadioButton();
        f35Btn = new javax.swing.JRadioButton();
        f36Btn = new javax.swing.JRadioButton();
        f37Btn = new javax.swing.JRadioButton();
        f11Btn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        answer1LblStatus = new javax.swing.JLabel();
        answer2LblStatus = new javax.swing.JLabel();
        answer3LblStatus = new javax.swing.JLabel();
        answer4LblStatus = new javax.swing.JLabel();
        answer5LblStatus = new javax.swing.JLabel();
        answer6LblStatus = new javax.swing.JLabel();
        answer7LblStatus = new javax.swing.JLabel();
        answer8LblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Clarity");

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabel10.setText("Form Evaluation                    1 - No          2 - Inbetween          3 - Yes");

        jLabel2.setText("Do you not get enough Sleep?");

        jLabel3.setText("Do you not practice Physical Activities?");

        jLabel4.setText("Are you bad at Socialising?");

        jLabel5.setText("Are your Hobbies Harmful?");

        jLabel6.setText("How good are your Energy Levels?");

        jLabel7.setText("How bad is your Stress");

        jLabel8.setText("Do you like to drink Alcohol?");

        jLabel9.setText("Do you Smoke?");

        f12Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(f12Btn);
        f12Btn.setText("1");
        f12Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f12Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f12Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f12BtnActionPerformed(evt);
            }
        });

        f13Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(f13Btn);
        f13Btn.setText("1");
        f13Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f13Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f13Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f13BtnActionPerformed(evt);
            }
        });

        f38Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup8.add(f38Btn);
        f38Btn.setText("3");
        f38Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f38Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f38Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f38BtnActionPerformed(evt);
            }
        });

        f14Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup4.add(f14Btn);
        f14Btn.setText("1");
        f14Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f14Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f14Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f14BtnActionPerformed(evt);
            }
        });

        f15Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup5.add(f15Btn);
        f15Btn.setText("1");
        f15Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f15Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f15Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f15BtnActionPerformed(evt);
            }
        });

        f16Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup6.add(f16Btn);
        f16Btn.setText("1");
        f16Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f16Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f16Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f16BtnActionPerformed(evt);
            }
        });

        f17Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup7.add(f17Btn);
        f17Btn.setText("1");
        f17Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f17Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f17Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f17BtnActionPerformed(evt);
            }
        });

        f18Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup8.add(f18Btn);
        f18Btn.setText("1");
        f18Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f18Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f18Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f18BtnActionPerformed(evt);
            }
        });

        f21Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(f21Btn);
        f21Btn.setText("2");
        f21Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f21Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f21Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f21BtnActionPerformed(evt);
            }
        });

        f22Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(f22Btn);
        f22Btn.setText("2");
        f22Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f22Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f22Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f22BtnActionPerformed(evt);
            }
        });

        f23Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(f23Btn);
        f23Btn.setText("2");
        f23Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f23Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f23Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f23BtnActionPerformed(evt);
            }
        });

        f24Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup4.add(f24Btn);
        f24Btn.setText("2");
        f24Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f24Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f24Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f24BtnActionPerformed(evt);
            }
        });

        f25Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup5.add(f25Btn);
        f25Btn.setText("2");
        f25Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f25Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f25Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f25BtnActionPerformed(evt);
            }
        });

        f26Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup6.add(f26Btn);
        f26Btn.setText("2");
        f26Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f26Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f26Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f26BtnActionPerformed(evt);
            }
        });

        f27Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup7.add(f27Btn);
        f27Btn.setText("2");
        f27Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f27Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f27Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f27BtnActionPerformed(evt);
            }
        });

        f28Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup8.add(f28Btn);
        f28Btn.setText("2");
        f28Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f28Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f28Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f28BtnActionPerformed(evt);
            }
        });

        f31Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(f31Btn);
        f31Btn.setText("3");
        f31Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f31Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f31Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f31BtnActionPerformed(evt);
            }
        });

        f32Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(f32Btn);
        f32Btn.setText("3");
        f32Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f32Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f32Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f32BtnActionPerformed(evt);
            }
        });

        f33Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup3.add(f33Btn);
        f33Btn.setText("3");
        f33Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f33Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f33Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f33BtnActionPerformed(evt);
            }
        });

        f34Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup4.add(f34Btn);
        f34Btn.setText("3");
        f34Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f34Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f34Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f34BtnActionPerformed(evt);
            }
        });

        f35Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup5.add(f35Btn);
        f35Btn.setText("3");
        f35Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f35Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f35Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f35BtnActionPerformed(evt);
            }
        });

        f36Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup6.add(f36Btn);
        f36Btn.setText("3");
        f36Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f36Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f36Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f36BtnActionPerformed(evt);
            }
        });

        f37Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup7.add(f37Btn);
        f37Btn.setText("3");
        f37Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f37Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f37Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f37BtnActionPerformed(evt);
            }
        });

        f11Btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(f11Btn);
        f11Btn.setText("1");
        f11Btn.setMaximumSize(new java.awt.Dimension(99, 16));
        f11Btn.setMinimumSize(new java.awt.Dimension(99, 16));
        f11Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f11BtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        answer1LblStatus.setBackground(new java.awt.Color(255, 255, 204));
        answer1LblStatus.setText("- Answer Status -");

        answer2LblStatus.setText("- Answer Status -");

        answer3LblStatus.setText("- Answer Status -");

        answer4LblStatus.setText("- Answer Status -");

        answer5LblStatus.setText("- Answer Status -");

        answer6LblStatus.setText("- Answer Status -");

        answer7LblStatus.setText("- Answer Status -");

        answer8LblStatus.setText("- Answer Status -");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f13Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f23Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f33Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f12Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f22Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f32Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f11Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f21Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f31Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f14Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f24Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f34Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f15Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f25Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f35Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f16Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f26Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f36Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f17Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f27Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f37Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(f18Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f28Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(f38Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(answer7LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer6LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer5LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer4LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer3LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer2LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer1LblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(answer8LblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(f11Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f21Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f31Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer1LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(f12Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f22Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f32Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer2LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(f13Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f23Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f33Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer3LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f14Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f24Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f34Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer4LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(f15Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f25Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f35Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer5LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(f16Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f26Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f36Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer6LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(f17Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f27Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f37Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer7LblStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(f18Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f28Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f38Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer8LblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitBtn)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f11BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f11BtnActionPerformed
        if(f11Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f11BtnActionPerformed

    private void f12BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f12BtnActionPerformed
        if(f12Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f12BtnActionPerformed

    private void f13BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f13BtnActionPerformed
        if(f13Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f13BtnActionPerformed

    private void f14BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f14BtnActionPerformed
        if(f14Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f14BtnActionPerformed

    private void f15BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f15BtnActionPerformed
        if(f15Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f15BtnActionPerformed

    private void f16BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f16BtnActionPerformed
        if(f16Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f16BtnActionPerformed

    private void f17BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f17BtnActionPerformed
        if(f17Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f17BtnActionPerformed

    private void f18BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f18BtnActionPerformed
        if(f18Btn.isSelected()){
            System.out.println("Good Job!");
        }
    }//GEN-LAST:event_f18BtnActionPerformed

    private void f21BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f21BtnActionPerformed
        if(f21Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f21BtnActionPerformed

    private void f22BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f22BtnActionPerformed
        if(f22Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f22BtnActionPerformed

    private void f23BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f23BtnActionPerformed
        if(f23Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f23BtnActionPerformed

    private void f24BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f24BtnActionPerformed
        if(f24Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f24BtnActionPerformed

    private void f25BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f25BtnActionPerformed
        if(f25Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f25BtnActionPerformed

    private void f26BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f26BtnActionPerformed
        if(f26Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f26BtnActionPerformed

    private void f27BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f27BtnActionPerformed
        if(f27Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f27BtnActionPerformed

    private void f28BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f28BtnActionPerformed
        if(f28Btn.isSelected()){
            System.out.println("This needs a bit of improvement");
        }
    }//GEN-LAST:event_f28BtnActionPerformed

    private void f31BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f31BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f31BtnActionPerformed

    private void f32BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f32BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f32BtnActionPerformed

    private void f33BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f33BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f33BtnActionPerformed

    private void f34BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f34BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f34BtnActionPerformed

    private void f35BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f35BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f35BtnActionPerformed

    private void f36BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f36BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f36BtnActionPerformed

    private void f37BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f37BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f37BtnActionPerformed

    private void f38BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f38BtnActionPerformed
        if(f31Btn.isSelected()){
            System.out.println("It is best to seek Professional Help");
        }
    }//GEN-LAST:event_f38BtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        
        //https://www.youtube.com/watch?v=epdXrFEpoqQ
        //Link for Button Inputs and Code
        
        if(!f11Btn.isSelected() && !f21Btn.isSelected() && !f31Btn.isSelected() && !f21Btn.isSelected() && !f12Btn.isSelected()  && !f13Btn.isSelected()  && !f14Btn.isSelected()  && !f15Btn.isSelected()  && !f16Btn.isSelected()  && !f17Btn.isSelected() && !f18Btn.isSelected() && !f22Btn.isSelected() && !f23Btn.isSelected() && !f24Btn.isSelected() && !f25Btn.isSelected() && !f26Btn.isSelected() && !f27Btn.isSelected() && !f28Btn.isSelected() && !f32Btn.isSelected() && !f33Btn.isSelected() && !f34Btn.isSelected() && !f35Btn.isSelected() && !f36Btn.isSelected() && !f37Btn.isSelected() && !f38Btn.isSelected() ){
            JOptionPane.showMessageDialog(null,"Please Select and Answer");
    }else{
        if(f11Btn.isSelected()){
            answer1LblStatus.setText("Well Done! Keep it up!");
            }
        if(f21Btn.isSelected()){
            answer1LblStatus.setText("This needs a bit of Improvement");
            }
        if(f31Btn.isSelected()){
            answer1LblStatus.setText("It is best to seek Professional Help");
            }
        if(f12Btn.isSelected()){
            answer2LblStatus.setText("Well Done! Keep it up!");
            }
        if(f22Btn.isSelected()){
            answer2LblStatus.setText("This needs a bit of Improvement");
            }
        if(f32Btn.isSelected()){
            answer2LblStatus.setText("It is best to seek Professional Help");
            }
        if(f13Btn.isSelected()){
            answer3LblStatus.setText("Well Done! Keep it up!");
            }
        if(f23Btn.isSelected()){
            answer3LblStatus.setText("This needs a bit of Improvement");
            }
        if(f33Btn.isSelected()){
            answer3LblStatus.setText("It is best to seek Professional Help");
            }
        if(f14Btn.isSelected()){
            answer4LblStatus.setText("Well Done! Keep it up!");
            }
        if(f24Btn.isSelected()){
            answer4LblStatus.setText("This needs a bit of Improvement");
            }
        if(f34Btn.isSelected()){
            answer4LblStatus.setText("It is best to seek Professional Help");
            }
        if(f15Btn.isSelected()){
            answer5LblStatus.setText("Well Done! Keep it up!");
            }
        if(f25Btn.isSelected()){
            answer5LblStatus.setText("This needs a bit of Improvement");
            }
        if(f35Btn.isSelected()){
            answer5LblStatus.setText("It is best to seek Professional Help");
            }
        if(f16Btn.isSelected()){
            answer6LblStatus.setText("Well Done! Keep it up!");
            }
        if(f26Btn.isSelected()){
            answer6LblStatus.setText("This needs a bit of Improvement");
            }
        if(f36Btn.isSelected()){
            answer6LblStatus.setText("It is best to seek Professional Help");
            }
        if(f17Btn.isSelected()){
            answer7LblStatus.setText("Well Done! Keep it up!");
            }
        if(f27Btn.isSelected()){
            answer7LblStatus.setText("This needs a bit of Improvement");
            }
        if(f37Btn.isSelected()){
            answer7LblStatus.setText("It is best to seek Professional Help");
            }
        if(f18Btn.isSelected()){
            answer8LblStatus.setText("Well Done! Keep it up!");
            }
        if(f28Btn.isSelected()){
            answer8LblStatus.setText("This needs a bit of Improvement");
            }
        if(f38Btn.isSelected()){
            answer8LblStatus.setText("It is best to seek Professional Help");
            }
        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer1LblStatus;
    private javax.swing.JLabel answer2LblStatus;
    private javax.swing.JLabel answer3LblStatus;
    private javax.swing.JLabel answer4LblStatus;
    private javax.swing.JLabel answer5LblStatus;
    private javax.swing.JLabel answer6LblStatus;
    private javax.swing.JLabel answer7LblStatus;
    private javax.swing.JLabel answer8LblStatus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JRadioButton f11Btn;
    private javax.swing.JRadioButton f12Btn;
    private javax.swing.JRadioButton f13Btn;
    private javax.swing.JRadioButton f14Btn;
    private javax.swing.JRadioButton f15Btn;
    private javax.swing.JRadioButton f16Btn;
    private javax.swing.JRadioButton f17Btn;
    private javax.swing.JRadioButton f18Btn;
    private javax.swing.JRadioButton f21Btn;
    private javax.swing.JRadioButton f22Btn;
    private javax.swing.JRadioButton f23Btn;
    private javax.swing.JRadioButton f24Btn;
    private javax.swing.JRadioButton f25Btn;
    private javax.swing.JRadioButton f26Btn;
    private javax.swing.JRadioButton f27Btn;
    private javax.swing.JRadioButton f28Btn;
    private javax.swing.JRadioButton f31Btn;
    private javax.swing.JRadioButton f32Btn;
    private javax.swing.JRadioButton f33Btn;
    private javax.swing.JRadioButton f34Btn;
    private javax.swing.JRadioButton f35Btn;
    private javax.swing.JRadioButton f36Btn;
    private javax.swing.JRadioButton f37Btn;
    private javax.swing.JRadioButton f38Btn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
