/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quoteapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author marym
 */
public class QuoteGUI extends javax.swing.JFrame {

    private ArrayList<Quoted> quotediary;

    /**
     * Creates new form QuoteGUI
     */
    public QuoteGUI() {
        initComponents();
        authorLBL.setVisible(false);
        quoteLBL.setVisible(false);
        moodLBL.setVisible(false);
        feelingLBL.setVisible(false);
        authorTF.setVisible(false);
        quoteTF.setVisible(false);
        moodTF.setVisible(false);
        feelingTF.setVisible(false);
        quotediary = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        displayBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        dayTF = new javax.swing.JTextField();
        dayLBL = new javax.swing.JLabel();
        typeLBL = new javax.swing.JLabel();
        typeTF = new javax.swing.JTextField();
        quoteRB = new javax.swing.JRadioButton();
        diaryRB = new javax.swing.JRadioButton();
        authorLBL = new javax.swing.JLabel();
        quoteLBL = new javax.swing.JLabel();
        moodLBL = new javax.swing.JLabel();
        feelingLBL = new javax.swing.JLabel();
        authorTF = new javax.swing.JTextField();
        quoteTF = new javax.swing.JTextField();
        moodTF = new javax.swing.JTextField();
        feelingTF = new javax.swing.JTextField();
        saveBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell Nova", 0, 36)); // NOI18N
        jLabel1.setText("Clarity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        displayBTN.setText("Display ");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        dayTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTFActionPerformed(evt);
            }
        });

        dayLBL.setBackground(new java.awt.Color(204, 204, 255));
        dayLBL.setText("Day: ");

        typeLBL.setBackground(new java.awt.Color(204, 204, 255));
        typeLBL.setText("Type:");

        typeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTFActionPerformed(evt);
            }
        });

        choiceBG.add(quoteRB);
        quoteRB.setText("Quote");
        quoteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoteRBActionPerformed(evt);
            }
        });

        choiceBG.add(diaryRB);
        diaryRB.setText("Diary");
        diaryRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaryRBActionPerformed(evt);
            }
        });

        authorLBL.setBackground(new java.awt.Color(204, 204, 255));
        authorLBL.setText("Author:");

        quoteLBL.setBackground(new java.awt.Color(204, 204, 255));
        quoteLBL.setText("Quote:");

        moodLBL.setBackground(new java.awt.Color(204, 204, 255));
        moodLBL.setText("Mood:");

        feelingLBL.setBackground(new java.awt.Color(204, 204, 255));
        feelingLBL.setText("Feeling:");

        quoteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoteTFActionPerformed(evt);
            }
        });

        feelingTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feelingTFActionPerformed(evt);
            }
        });

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(typeLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                            .addComponent(dayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quoteLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moodLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayTF, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(typeTF)
                            .addComponent(authorTF)
                            .addComponent(quoteTF))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(feelingLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moodTF)
                            .addComponent(feelingTF))
                        .addGap(176, 176, 176)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diaryRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quoteRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(displayBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBTN)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLBL)
                    .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLBL)
                            .addComponent(typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLBL)
                            .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quoteLBL)
                            .addComponent(quoteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moodLBL)
                            .addComponent(moodTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feelingLBL)
                            .addComponent(feelingTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBTN)
                            .addComponent(searchBTN)
                            .addComponent(addBTN)
                            .addComponent(displayBTN)
                            .addComponent(saveBTN))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(quoteRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diaryRB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quoteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quoteTFActionPerformed

    private void dayTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTFActionPerformed

    private void quoteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoteRBActionPerformed
        // TODO add your handling code here:
        // when quote radio button is selected certain things will visible 
        authorLBL.setVisible(true);
        quoteLBL.setVisible(true);
        moodLBL.setVisible(false);
        feelingLBL.setVisible(false);
        authorTF.setVisible(true);
        quoteTF.setVisible(true);
        moodTF.setVisible(false);
        feelingTF.setVisible(false);
    }//GEN-LAST:event_quoteRBActionPerformed

    private void diaryRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaryRBActionPerformed
        // TODO add your handling code here:
        //when diary radio button is selected certain things will be visible
        authorLBL.setVisible(false);
        quoteLBL.setVisible(false);
        moodLBL.setVisible(true);
        feelingLBL.setVisible(true);
        authorTF.setVisible(false);
        quoteTF.setVisible(false);
        moodTF.setVisible(true);
        feelingTF.setVisible(true);
    }//GEN-LAST:event_diaryRBActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // add quote or diay log depending on which radio button is selected different things will be visible
        if (quoteRB.isSelected()) {
            Quote a = new Quote();
            a.setDay(dayTF.getText());
            a.setType(typeTF.getText());
            a.setQuote1(quoteTF.getText());
            a.setAuthor(authorTF.getText());
            quotediary.add(a);
            
        } else if {(diaryRB.isSelected()) {
            Diary b = new Diary();
            b.setDay(dayTF.getText());
            b.setType(typeTF.getText());
            b.setMood(moodTF.getText());
            b.setFeelings(feelingTF.getText());
            quotediary.add(b);
        }
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // displays the info 
        for (Quoted q : quotediary) {
            JOptionPane.showMessageDialog(null, q.getInfo());
        }
    }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // seach using day 
         if(quotediary.isEmpty()){
            JOptionPane.showMessageDialog(null,"Sorry, there are nothing to search");
        }
        else{
            String searchTerm = JOptionPane.showInputDialog(null, "Please enter an day to search");
            for(Quoted q:quotediary){
                if(q.getDay().equalsIgnoreCase(searchTerm)){
                    JOptionPane.showMessageDialog(null,q.getDay());
}
}
}
             
    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // search day and if itfs that day itll delete all the info of that
  if(quotediary.isEmpty()){
            JOptionPane.showMessageDialog(null,"Sorry, there are nothing to delete");
        }
        else{
            String searchTerm = JOptionPane.showInputDialog(null, "Please enter an day to delete");
            for(Quoted q:quotediary){
                if(q.getDay().equalsIgnoreCase(searchTerm)){
                    employees.remove(q);
                    JOptionPane.showMessageDialog(null,q.getInfo()+" has been deleted.");
                }
            }
        }     
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // to save information to a file 
       File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
           f =  new File("output.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(quotediary);
            oStream.close();
        }
        catch(IOException q){
            System.out.println(q);
        }


    }//GEN-LAST:event_saveBTNActionPerformed

    private void typeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTFActionPerformed

    private void feelingTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feelingTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feelingTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuoteGUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuoteGUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuoteGUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuoteGUI.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuoteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel authorLBL;
    private javax.swing.JTextField authorTF;
    private javax.swing.ButtonGroup choiceBG;
    private javax.swing.JLabel dayLBL;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JRadioButton diaryRB;
    private javax.swing.JButton displayBTN;
    private javax.swing.JLabel feelingLBL;
    private javax.swing.JTextField feelingTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel moodLBL;
    private javax.swing.JTextField moodTF;
    private javax.swing.JLabel quoteLBL;
    private javax.swing.JRadioButton quoteRB;
    private javax.swing.JTextField quoteTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel typeLBL;
    private javax.swing.JTextField typeTF;
    // End of variables declaration//GEN-END:variables
}
